strict: true

site_name: "Docs â¸¬ BioTorrents.de"
site_url: "https://docs.biotorrents.de"

repo_url: "https://github.com/biotorrents/gazelle"
edit_uri: ""

nav:
  - "index.md"
  - "torrents.md"
  - "users.md"
  - "forums.md"
  - "meta.md"
  - "install.md"

markdown_extensions:
  - smarty
